export const ADD_SEARCH = 'ADD_SEARCH';
export const RECENT_SEARCHES = 'RECENT_SEARCHES';
export const CLEAR_RECENT_SEARCHES = 'CLEAR_RECENT_SEARCHES';
export const SUGGESTION = 'SUGGESTION';
export const SUGGESTION_ITEMS= 'SUGGESTION_ITEMS';
export const RECOMMENDED= 'RECOMMENDED';
export const LOADING= 'LOADING';